### PR TITLE
[FIX] [16.0] sale_margin_delivered: Fix calculation when more quantities are sent than ordered

### PR DESCRIPTION
**Pull request by Shide**
When sending more quantities than ordered, `purchase_price_delivery` field is not calculated correctly in this Odoo version.

Now, instead of use unit_cost of valuation layer, value / quantity is used instead.
Refunds are already taken in consideration in valuation layers.
Before, only the first valuation layer is taken in consideration, now all valuation layers are considered. (FIFO product valuation and one move needs to be splitted in 2 stock.move.lines and each move line has different lots with different values)

Also added tests, more concise translations and "help" to fields to know exactly what does.

https://www.loom.com/share/9cc8c826b8054b62a508d561632b837c?sid=ce29f0dd-9fd4-40bd-b615-4f775f42b339

MT-6136 @moduon @yajo @EmilioPascual  @rafaelbn @sergio-teruel please review if you want :)

### CODE REVIEW

**Review by yajo — APPROVED** [review]

**Review by Gelojr — APPROVED** [review]
Nice @Shide LGTM

**Review by sergio-teruel — APPROVED** [review]

**Comment by yajo** [comment]
Could you merge please @sergio-teruel? I don't have permission here

**Comment by sergio-teruel** [comment]
Ohhh!! I'm not a PSC... :sob:

**Comment by rafaelbn** [comment]
Hello all! @sergio-teruel @Gelojr @yajo @Gelojr !

I've reviewed and I have doubts in cost price delivered and a better order in columns 😇 

This is my video review (1.5x is 5 minutes)

https://www.loom.com/share/3ffc172466d24629bee5247cdb89f9f6?sid=f0146094-5bf3-4798-936f-5ea6bc32810e

🙏🏼 Thank you! Reviewing with ❤️ 😄 

imagen

**Comment by Gelojr** [comment]
> Hello all! @sergio-teruel @Gelojr @yajo @Gelojr !
> 
> I've reviewed and I have doubts in cost price delivered and a better order in columns 😇
> 
> This is my video review (1.5x is 5 minutes)
> 
> https://www.loom.com/share/3ffc172466d24629bee5247cdb89f9f6?sid=f0146094-5bf3-4798-936f-5ea6bc32810e
> 
> 🙏🏼 Thank you! Reviewing with ❤️ 😄
> 
> imagen

I believe that the Cost price dlvd. column should appear, since it is the total cost of what is delivered. It seems that it is not calculated correctly, since it is calculating the cost of the quantity ordered.

**Comment by Shide** [comment]
> Hello all! @sergio-teruel @Gelojr @yajo @Gelojr !
> 
> I've reviewed and I have doubts in cost price delivered and a better order in columns 😇
> 
> This is my video review (1.5x is 5 minutes)
> 
> https://www.loom.com/share/3ffc172466d24629bee5247cdb89f9f6?sid=f0146094-5bf3-4798-936f-5ea6bc32810e
> 
> 🙏🏼 Thank you! Reviewing with ❤️ 😄
> 
> imagen

Those columns are not duplicated, but in your case, you are using Standard or AVCO product valuation.
Those columns are not meaningfull in your context, but in a FIFO valuation should change a bit. 

In any case, for the commercial user, Cost and Margin are welcome because they cannot see dlvd. margins when doing the quotation. 
If commercial user receives a % extra payment for each sale based on the margin (assume margin dlvd. because cost can be modified freely on the line) and valuations are Standard or AVCO, they can assume that dlvd. cost and margins are going to be the same as sale cost and margins.

Then,
- for commercial users: hide dlvd. columns and not modify cost in the sale line (because they are not going to receive more %).
- for reporter users: hide cost and margin columns and show dlvd. columns because they need to see the real value of the delivered quantities to calculate % extra payments.

Since all columns can be used for different type of users and Odoo allows to custom tree columns per user, the code as it is will work for a variety of roles. 
I won't add anything more. Just inform users that what do each column and what are suggested columns to see on each role.

**Comment by rafaelbn** [comment]
After discussing with @Shide , this ho ahead as resolves BUG and later we could improve it.

Thank you!! 😃

**Review by rafaelbn — APPROVED** [review]
/ocabot merge patch

**Pull request merged**
