### PR TITLE
[13.0][IMP] account_invoice_margin: Add Cost price measure to Invoices Analysis

### PR DESCRIPTION
**Pull request by victoralmau**
Add Cost price measure to Invoices Analysis (unitary cost price).

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT30685

### CODE REVIEW

**Comment by pedrobaeza** [comment]
The name "Purchase Price" is misleading, as it's not that one, but "Cost Price".

**Comment by victoralmau** [comment]
> The name "Purchase Price" is misleading, and it's not that one, but "Cost Price".

Excuse me, you mean change the field name (cost_price) or string?

**Comment by pedrobaeza** [comment]
At least the label. For the field name, follow the `sale_margin` convention. I also wonder if it's the unitary cost price or the subtotal one.

**Comment by victoralmau** [comment]
I have already changed the label. It's unitary cost price.

**Comment by pedrobaeza** [comment]
Then it doesn't have too much sense to be sum. I also doubt the usefulness of this field. I would close this and wait for the need of this.

**Pull request closed without merging**
