### PR TITLE
[14.0][MIG] sale_margin_security: Migration to 14.0

### PR DESCRIPTION
**Pull request by rafamarpe**
We have removed the write method from sale_order, we believe it's no longer necessary.
We have added security in the margin field of the sales report

### CODE REVIEW

**Comment by rafamarpe** [comment]
Hello @pedrobaeza.
I'm migrating this module.

**Comment by pedrobaeza** [comment]
For next times, please put correctly the PR title as I have done here.

/ocabot migration sale_margin_security

**Review by sergio-teruel — APPROVED** [review]

**Review by CarlosRoca13 — APPROVED** [review]
LGTM :+1: Thanks

**Pull request merged**
