### PR TITLE
[MIG][11.0] Migrate sale_order_margin_percent

### PR DESCRIPTION
**Pull request by i-vyshnevska**
supressed https://github.com/OCA/sale-workflow/pull/1012

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]
Code review. No test. Thanks.

**Comment by nikul-serpentcs** [comment]
@i-vyshnevska `Mr. Travis` is Angry :red_circle:

**Comment by i-vyshnevska** [comment]
@nikul-serpentcs thanks, done

**Review by nikul-serpentcs — APPROVED** [review]
Squash Last Commit, Otherwise Code Review LGTM :+1:

**Review by legalsylvain — APPROVED** [review]
Lgtm. Code review. No test.

**Pull request merged**
