### PR TITLE
[16.0][FW-PORT][IMP] sale_margin_security: Avoid display margin in measures pivot view.

### PR DESCRIPTION
**Pull request by ValentinVinagre**
Forward-port of https://github.com/OCA/margin-analysis/pull/188

Set group_sale_margin_security in all sensible fields.

### CODE REVIEW

**Comment by ValentinVinagre** [comment]
@HaraldPanten

**Comment by pedrobaeza** [comment]
Please mention the PR that this is a fw-port of. This helps to speed up reviews.

**Comment by ValentinVinagre** [comment]
> Please mention the PR that this is a fw-port of. This helps to speed up reviews.

done 😄

**Review by HaraldPanten — APPROVED** [review]
Functional review in runboat

**Review by pedrobaeza — APPROVED** [review]
I was talking about putting this:

Selección_022

but I have already done it.

/ocabot merge major

**Comment by ValentinVinagre** [comment]
> I was talking about putting this:
> 
> Selección_022
> 
> but I have already done it.
> 
> /ocabot merge major

For the next few times I will keep it in mind, I didn't know how it was managed :) thanks Pedro.

**Pull request merged**
