### PR TITLE
[13.0][FIX] sale_margin_delivered: Delivered values not zero when sale line…

### PR DESCRIPTION
**Pull request by carlosdauden**
… has not quantity delivered

@Tecnativa TT26105

### CODE REVIEW

**Comment by carlosdauden** [comment]
@sergio-teruel can you review?

**Review by sergio-teruel — APPROVED** [review]

**Comment by pedrobaeza** [comment]
Can you please check why Travis is red?

**Comment by carlosdauden** [comment]
Travis green

**Review by victoralmau — APPROVED** [review]

**Comment by sergio-teruel** [comment]
Ready for merge??

**Pull request merged**
