### PR TITLE
[16.0][MIG] product_pricelist_margin: Migration to version 16.0 #168 #173

### PR DESCRIPTION
**Pull request by hugo-cordoba**
[16.0][MIG] product_pricelist_margin

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
Hi @HugoCordobaLeal. Thanks for porting this module. 

Unfortunately, this module is obsolete, and should not be ported. 
See : https://github.com/OCA/product-attribute/pull/1114#issuecomment-1183158388

The objective, in V16 is to develop a module named ``product_pricelist_simulation_margin`` on top of the module ``product_pricelist_simulation``.  That is a base module to simulate pricelist prices.

I'm OK to develop this module.

@pedrobaeza, ernestotejeda : did you planned to migrate ``product_pricelist_simulation`` in V16 ?

**Comment by hugo-cordoba** [comment]
Good morning. 

Ok, the migration is not finished yet, I would have to modify some things and fix the tests. I didn't know there was another intention in v16. If the new version requires to develop the module 'product_pricelist_simulation_margin', I offer to be the author of that module.

What do you think about @pedrobaeza ?

cc/ @legalsylvain

**Comment by pedrobaeza** [comment]
Go ahead, Hugo! Please check how `product_pricelist_simulation` is working now, and the new module will be trivial adding the column.

**Comment by legalsylvain** [comment]
@pedrobaeza : product_pricelist_simulation is available for V16 ? I didn't found it any pending work.

For me [the last available version is in V13](https://github.com/OCA/product-attribute/tree/13.0/product_pricelist_simulation#product-pricelist-simulation), and there is [a dead PR for V14 here](https://github.com/OCA/product-attribute/pull/1257).

**Comment by pedrobaeza** [comment]
Well, then migrating that module is a pre-requisite

**Pull request closed without merging**
