### PR TITLE
MIGR 12 sale margin percent

### PR DESCRIPTION
**Pull request by bealdav**
Standard migration

cc @SimoRubi @i-vyshnevska  @acm1pt-colorado

### CODE REVIEW

**Review by legalsylvain — CHANGES_REQUESTED** [review]
thanks for porting this module.

Please check travis. the migration is broken, due to dependency to new module ``uom``.

regards.

**Review by SimoRubi — CHANGES_REQUESTED** [review]
Thanks for the PR!
Please check travis: https://travis-ci.org/OCA/margin-analysis/jobs/625775081#L1139

**Review by robinkeunen — APPROVED** [review]
Looks good to me.

**Review by PierrickBrun — APPROVED** [review]

**Pull request merged**
