### PR TITLE
[MIG] sale_margin_sync: Migration to 12.0

### PR DESCRIPTION
**Pull request by carlosdauden**
@Tecnativa TT19351

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Let's go now for v13!

**Review by sergio-teruel — CHANGES_REQUESTED** [review]
Can you change tests for 100% coverage, please

**Comment by carlosdauden** [comment]
coverege 100%

**Comment by pedrobaeza** [comment]
Thanks for extra coverage. Let's merge it then and go for v13

/ocabot merge

**Pull request merged**
