### PR TITLE
[16.0][MIG] account_invoice_margin_sale: Migration to 16.0

### PR DESCRIPTION
**Pull request by ljsalvatierra-factorlibre**
Pending review of:
- https://github.com/OCA/margin-analysis/pull/163

### CODE REVIEW

**Comment by Gelo-fl** [comment]
@ljsalvatierra-factorlibre runboat does not work to be able to test it.

**Comment by ljsalvatierra-factorlibre** [comment]
> @ljsalvatierra-factorlibre runboat does not work to be able to test it.

I think its because the dependency is not merged yet.

**Comment by rafaelbn** [comment]
Please @ljsalvatierra-factorlibre rebase! 😄 dependency is merged!

**Comment by ljsalvatierra-factorlibre** [comment]
> Please @ljsalvatierra-factorlibre rebase! smile dependency is merged!

Done, apologies for the delay.

**Comment by ljsalvatierra-factorlibre** [comment]
Still WIP awaiting functional review.

**Comment by RodrigoBM** [comment]
ping @rafaelbn @fcvalgar

**Review by fcvalgar — APPROVED** [review]
Functional review including user permissions.

LGTM, thankx @ljsalvatierra-factorlibre 

image

**Comment by ljsalvatierra-factorlibre** [comment]
> Functional review including user permissions.
> 
> LGTM, thankx @ljsalvatierra-factorlibre
> 
> image

thank you :)

Still pending review from @Gelo-fl

**Review by RodrigoBM — APPROVED** [review]

**Pull request merged**
