### PR TITLE
In product.price.type do not set company_id required

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
I set company_id optional.

I think, the context can be sufficient to know which price take. With a required company_id it is difficult to use pricelist inheritence.

For example a base price list for all my company which contains product with same price for all. And one pricelist per company with specific price for product or based on the general pricelist.

### CODE REVIEW

**Comment by lmignon** [comment]
:+1: LGTM; failing tests seems to be unrelated

**Comment by rvalyi** [comment]
:+1:  LGTM

**Comment by pedrobaeza** [comment]
Security rule it's also valid for this condition, so :+1:

**Comment by laetitia-gangloff** [comment]
Thank you !

**Pull request merged**
