### PR TITLE
[13.0] [MIG] sale_order_margin_percent

### PR DESCRIPTION
**Pull request by Rad0van**
Straightforward migration

### CODE REVIEW

**Comment by legalsylvain** [comment]
Hi @Rad0van. Thanks for porting this module.
could you add in a roadmap.rst file to do not port this module in V14 to avoid useless work.
(Ref : https://twitter.com/legalsylvain/status/1302957261564841989)

kind regards.

**Comment by Rad0van** [comment]
> Hi @Rad0van. Thanks for porting this module.
> could you add in a roadmap.rst file to do not port this module in V14 to avoid useless work.
> (Ref : https://twitter.com/legalsylvain/status/1302957261564841989)
> 
> kind regards.

Done.

**Review by legalsylvain — APPROVED** [review]
thanks.

code review / no test.

**Comment by Rad0van** [comment]
Please do not merge this yet - it crashes in frontend in some cases - for example also when there is no sale order line :-( Will investigate and fix...

**Comment by Rad0van** [comment]
Should be OK now. Please review.

**Review by wtaferner — APPROVED** [review]

**Comment by mourad-ehm** [comment]
Hi thanks for this PR.
Could you see this improvement https://github.com/OCA/margin-analysis/pull/88

**Comment by Rad0van** [comment]
> Hi thanks for this PR.
> Could you see this improvement #88

@mourad-ehm nice. I created a separate module just for that but I guess it makes more sense this way. But it seems Travis is failing on one of the builds. Can you check? Also what is the best way here? Do the migration and then apply the improvement? Or do both at the same time? @wtaferner & @legalsylvain any opinion? If first, could you please merge this? Thanx

**Comment by mourad-ehm** [comment]
I think, it make sense to apply improvement in the same time of migration. To facilitate migration between 12.0 and 13.0 I can close this PR   #88  and will be content with improvement in v 13. 
What do you think @legalsylvain @wtaferner  ?

**Comment by mourad-ehm** [comment]
@ping @pedrobaeza

**Comment by pedrobaeza** [comment]
As the other improvement is not yet merged in v12, let's continue merging this and it can be added later if proper for not blocking more time the arrival of the module to v13 and not forcing the contributor to more effort:

/ocabot merge nobump

**Pull request merged**
