### PR TITLE
[14.0][MIG] sale_margin_security: Migration to 14.0

### PR DESCRIPTION
**Pull request by rafamarpe**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Thanks for the contribution.

Please preserve commit history following technical method explained in https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0.

If the jump is between several versions, you have to modify the source branch in the main command to accommodate it to this circumstance.

**Comment by rafamarpe** [comment]
Thanks @pedrobaeza I will try

**Comment by rafamarpe** [comment]
Hi, @pedrobaeza
Excuse me, do you mean follow all this part?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

**Comment by rafamarpe** [comment]
Hi, @pedrobaeza
Excuse me, do you mean follow all this part?
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#technical-method-to-migrate-a-module-from-130-to-140-branch

**Comment by pedrobaeza** [comment]
Yes

**Pull request closed without merging**
