### PR TITLE
[MIG][13.0] account_invoice_margin_sale: Migration to v13.0

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa TT21604

### CODE REVIEW

**Review by legalsylvain — APPROVED** [review]

**Comment by Tardo** [comment]
Check Travis

**Comment by sergio-teruel** [comment]
@Tardo travis fixed!!!

**Comment by sergio-teruel** [comment]
ping @carlosdauden

**Review by carlosdauden — APPROVED** [review]

**Pull request merged**
