### PR TITLE
fix flake8 warnings

### PR DESCRIPTION
**Pull request by gurneyalex**
Mostly folding lines and fiddling with missing / superfluous spaces.
On a couple occastion, adding an intermediate variable or removing an
unused one.

### CODE REVIEW

**Comment by yvaucher** [comment]
Almost done only few pep8 errors remaining

./product_historical_margin_report/**init**.py:22:1: W391 blank line at end of file
./product_standard_margin/**init**.py:22:1: W391 blank line at end of file
./product_price_history/**init**.py:3:2: W291 trailing whitespace
./product_price_history/**init**.py:19:75: W291 trailing whitespace
./product_price_history/**init**.py:24:21: W292 no newline at end of file
./product_price_history/wizard/**init**.py:3:2: W291 trailing whitespace
./product_price_history/wizard/**init**.py:19:75: W291 trailing whitespace
./product_price_history/wizard/**init**.py:24:1: W391 blank line at end of file
./product_cost_incl_bom_price_history/**init**.py:3:2: W291 trailing whitespace
./product_cost_incl_bom_price_history/**init**.py:19:75: W291 trailing whitespace

**Comment by pedrobaeza** [comment]
PEP8 is fixed, so :+1: 

There's still errors on tests, to resolve in other PR.

Regards.

**Comment by yvaucher** [comment]
:+1:

**Comment by rvalyi** [comment]
:+1:

**Pull request merged**
