### PR TITLE
[16.0][FIX] sale_margin_delivered_security: Add security groups to right fi…

### PR DESCRIPTION
**Pull request by lmignon**
…elds

The fields to secure are defined on the sale.order.line model not on sale.order

### CODE REVIEW

**Review by yajo — APPROVED** [review]
Good catch!

**Comment by yajo** [comment]
Please @rafaelbn @gelojr @fcvalgar do a functional review.

**Review by EmilioPascual — APPROVED** [review]

**Comment by rafaelbn** [comment]
@moduon MT-5158 Functional team will review today, thank you! 😄

**Review by fcvalgar — APPROVED** [review]
Functional review,

LGTM, thank ypu @lmignon

**Review by Shide — APPROVED** [review]

**Comment by lmignon** [comment]
@OCA/accounting-maintainers someone to merge this one plz?

**Pull request merged**
