### PR TITLE
[FIX] sale_margin_delivered: Fix compute avco from stock valuation layer instead of stock move

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why `move.price_unit` is not reliable?

**Comment by sergio-teruel** [comment]
Odoo V13.0 for outgoing moves from sales does not store this field. Now is stored into stock valuation layer model.
So price_unit stock_move field for sales moves always is zero..

**Comment by sergio-teruel** [comment]
I will explainit into code moule...

**Comment by pedrobaeza** [comment]
Thanks for the explanation. In this case, I would say to put that explanation in the commit message instead of the code, but in code can also serve for explanation. As you prefer.

**Review by pedrobaeza — APPROVED** [review]

**Review by marcelsavegnago — APPROVED** [review]

**Pull request merged**
