### PR TITLE
[15.0][MIG] sale_margin_security: Migration to 15.0

### PR DESCRIPTION
**Pull request by CarlosRoca13**
cc @Tecnativa TT36519

please @sergio-teruel @chienandalu review this

### CODE REVIEW

**Review by chienandalu — APPROVED** [review]
Code and functional test :+1: 

pre-commit seems to be broken for this branch

**Comment by CarlosRoca13** [comment]
Yes, I fix it in this PR :smile: https://github.com/OCA/margin-analysis/pull/148

**Review by sergio-teruel — APPROVED** [review]

**Comment by chienandalu** [comment]
> Yes, I fix it in this PR smile #148

Ok, can you rebase :)

**Comment by pedrobaeza** [comment]
No need to rebase. The bot does for you:

/ocabot merge nobump
/ocabot migration sale_margin_security

**Pull request merged**
