### PR TITLE
Allow to write 0 in historized field

### PR DESCRIPTION
**Pull request by laetitia-gangloff**
Hello,

it is not possible to write 0 in standard_price.

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Is Travis error related?

**Comment by laetitia-gangloff** [comment]
@pedrobaeza It seems not, it is about some fields not filled.

I will check that.

**Comment by clonedagain** [comment]
We're trying to fix the unrelated errors at https://github.com/OCA/margin-analysis/issues/13: you can help there because I'm totally clueless for the moment.

**Comment by guewen** [comment]
The change seems correct to me :+1: 
Thanks

**Comment by yvaucher** [comment]
:+1:

**Pull request merged**
