### PR TITLE
[11.0][IMP] sale_margin_delivered: Avoid use product_uom_qty to compute delivered margin. Other module tests fails

### PR DESCRIPTION
**Pull request by sergio-teruel**
cc @Tecnativa

### CODE REVIEW

**Review by pedrobaeza — APPROVED** [review]
Fast-tracking when CIs finish

**Comment by pedrobaeza** [comment]
Travis is red, @sergio-teruel

**Comment by sergio-teruel** [comment]
Ready

**Review by rafaelbn — APPROVED** [review]
:+1:

**Pull request merged**
