### PR TITLE
[10.0] .travis.yml: Update to latest definition

### PR DESCRIPTION
**Pull request by FFernandez-PlanetaTIC**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
You can take the occasion to update whole template, removing one build and all the Transifex stuff.

**Comment by FFernandez-PlanetaTIC** [comment]
I will try not to break anything...

**Comment by FFernandez-PlanetaTIC** [comment]
`sale_line_cost_control` tests fail...

https://travis-ci.org/OCA/margin-analysis/jobs/565525241#L763
https://travis-ci.org/OCA/margin-analysis/jobs/565525242#L763

**Comment by pedrobaeza** [comment]
This is something that happens because Odoo added an extra constraint when changing currency. What you can do it to set the currency by SQL in the tests as a workaround. It's what we have made in other repositories, but right now, I don't find any example.

**Pull request merged**
